
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild のバージョン 17.7.2+d6990bcfa (.NET Framework)
      2024/01/05 1:41:58 にビルドを開始しました。
      
      ノード 1 上のプロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdC.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を作成しています。
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" のタッチ タスクを実行しています。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.59
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/3.27.8/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild のバージョン 17.7.2+d6990bcfa (.NET Framework)
      2024/01/05 1:41:59 にビルドを開始しました。
      
      ノード 1 上のプロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdCXX.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を作成しています。
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" のタッチ タスクを実行しています。
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\3.27.8\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.45
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/3.27.8/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-b6mfq4"
      binary: "C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-b6mfq4"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-b6mfq4'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_87687.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild のバージョン 17.7.2+d6990bcfa (.NET Framework)
        2024/01/05 1:42:00 にビルドを開始しました。
        
        ノード 1 上のプロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-b6mfq4\\cmTC_87687.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_87687.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-b6mfq4\\Debug\\" を作成しています。
          ディレクトリ "cmTC_87687.dir\\Debug\\cmTC_87687.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_87687.dir\\Debug\\cmTC_87687.tlog\\unsuccessfulbuild" を作成しています。
          "cmTC_87687.dir\\Debug\\cmTC_87687.tlog\\unsuccessfulbuild" のタッチ タスクを実行しています。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_87687.dir\\Debug\\\\" /Fd"cmTC_87687.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Users\\tahar\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_87687.dir\\Debug\\\\" /Fd"cmTC_87687.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Users\\tahar\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-b6mfq4\\Debug\\cmTC_87687.exe" /INCREMENTAL /ILK:"cmTC_87687.dir\\Debug\\cmTC_87687.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-b6mfq4/Debug/cmTC_87687.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-b6mfq4/Debug/cmTC_87687.lib" /MACHINE:X64  /machine:x64 cmTC_87687.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_87687.vcxproj -> C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-b6mfq4\\Debug\\cmTC_87687.exe
        FinalizeBuildStatus:
          ファイル "cmTC_87687.dir\\Debug\\cmTC_87687.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_87687.dir\\Debug\\cmTC_87687.tlog\\cmTC_87687.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-b6mfq4\\cmTC_87687.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.43
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/tahar/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-pssk94"
      binary: "C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-pssk94"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-pssk94'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_7b34a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild のバージョン 17.7.2+d6990bcfa (.NET Framework)
        2024/01/05 1:42:01 にビルドを開始しました。
        
        ノード 1 上のプロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-pssk94\\cmTC_7b34a.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_7b34a.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-pssk94\\Debug\\" を作成しています。
          ディレクトリ "cmTC_7b34a.dir\\Debug\\cmTC_7b34a.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_7b34a.dir\\Debug\\cmTC_7b34a.tlog\\unsuccessfulbuild" を作成しています。
          "cmTC_7b34a.dir\\Debug\\cmTC_7b34a.tlog\\unsuccessfulbuild" のタッチ タスクを実行しています。
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7b34a.dir\\Debug\\\\" /Fd"cmTC_7b34a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\tahar\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.37.32825 for x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7b34a.dir\\Debug\\\\" /Fd"cmTC_7b34a.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Users\\tahar\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-pssk94\\Debug\\cmTC_7b34a.exe" /INCREMENTAL /ILK:"cmTC_7b34a.dir\\Debug\\cmTC_7b34a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-pssk94/Debug/cmTC_7b34a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Workspace/myCLionWorks/RealTimeDataPlotter/cmake-build-debug-visual-studio/CMakeFiles/CMakeScratch/TryCompile-pssk94/Debug/cmTC_7b34a.lib" /MACHINE:X64  /machine:x64 cmTC_7b34a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_7b34a.vcxproj -> C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-pssk94\\Debug\\cmTC_7b34a.exe
        FinalizeBuildStatus:
          ファイル "cmTC_7b34a.dir\\Debug\\cmTC_7b34a.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_7b34a.dir\\Debug\\cmTC_7b34a.tlog\\cmTC_7b34a.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\Workspace\\myCLionWorks\\RealTimeDataPlotter\\cmake-build-debug-visual-studio\\CMakeFiles\\CMakeScratch\\TryCompile-pssk94\\cmTC_7b34a.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.41
        
      exitCode: 0
...
